services:
  - type: web
    name: musicfinder-backend
    runtime: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ACR_ACCESS_KEY
        sync: false
      - key: ACR_ACCESS_SECRET
        sync: false
      - key: ACR_HOST
        sync: false